name: open_lift_2
description: Community driven fitness tracker with AI coaching.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  
# State Management
  provider: ^6.0.0
  
# Backend & Local DB
  supabase_flutter: ^2.0.0
  sqflite: ^2.3.0
  path: ^1.8.3
  sqflite_common_ffi: ^2.3.0
  
# UI Components
  google_fonts: ^6.1.0
  fl_chart: ^0.63.0
  flutter_markdown: ^0.6.14
  percent_indicator: ^4.2.3
  
# Utilities
  uuid: ^4.0.0
  shared_preferences: ^2.2.0
  google_generative_ai: ^0.4.6
  audioplayers: ^5.2.1
  wakelock_plus: ^1.1.0
  flutter_dotenv: ^5.1.0 
  intl: ^0.18.0
  
# Offline Polish
  cached_network_image: ^3.3.0
  connectivity_plus: ^5.0.2
  path_provider: ^2.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  supabase: ^2.0.0
  dotenv: ^4.2.0         
  http: ^1.6.0

flutter:
  uses-material-design: true
  assets:               
    - .env
    - assets/data/exercises.json
    - assets/beep.mp3
    - assets/beep_long.mp3 